version: '{build}'
platform:
  - x86
  - x64
environment:
  URHO3D_D3D11: 1
  matrix:
    - BUILD_SHARED_LIBS: OFF
    - BUILD_SHARED_LIBS: ON
before_build:
  - mkdir "%APPVEYOR_BUILD_FOLDER%\Build"
  - cd "%APPVEYOR_BUILD_FOLDER%\Build"
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\Urho3D-SDK" ..
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\Build"
  - cmake --build . --target install
after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - 7z a Urho3D-SDK.7z "%APPVEYOR_BUILD_FOLDER%\Urho3D-SDK"
test: off
artifacts:
  path: Urho3D-SDK.7z
